name: agrolink
description: Agrolink - Gestão Rural

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  http: ^1.2.1
  http_parser: ^4.0.2
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  flutter_svg: ^2.0.17
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg